# Generated by Django 2.2.20 on 2022-05-13 14:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Цена')),
                ('image', models.FileField(help_text='Изображение (jpg, png)', max_length=255, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])])),
                ('sale_percent', models.IntegerField(blank=True, null=True, verbose_name='Процент скидки')),
                ('white_name_sale', models.BooleanField(default=False, verbose_name='Белый цвет названия/скидки')),
                ('show_in_slider', models.BooleanField(default=False, verbose_name='Показать в слайдере')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='Рекомендуемый товар')),
                ('is_new_year_sale', models.BooleanField(default=False, verbose_name='Новогодняя скидка')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
